add adapter for YAML input
metrumresearchgroup/mrgvalprep pull request #23
Opened 2022-02-04 19:53 UTC by kyleam

Support reading stories and requirements from YAML files.

cc @kylebaron

2022-02-08 16:22 UTC, seth127 reviewed
I looked through the code but won't have time to run it today. All the test cases and spec, etc. look good to me. @kylebaron if you're waiting on this, you can feel free to pull it and test it on your stuff and approve the PR as you see fit. Otherwise, I should be able to get to it tomorrow or the next day.

2022-02-09 15:30 UTC, seth127 requested changes
Mostly looks great. A few minor things on the test suite.

2022-02-09 15:30 UTC, seth127 commented on inst/yaml-input/stories-only-1.yaml
> +    S001 description
minor thing, but this should be `S002 description` (same with `S003` in other test file). This tripped me up when looking at these test results manually and seeing that whole column was the same.

2022-02-09 15:30 UTC, seth127 commented on R/read-spec-yaml.R
> +#' @param stories,requirements Character vector of YAML files to read stories
I had initially thought we would pass a dir here, but I guess this option is actually better. If you want everything in the dir you can easily to `stories = list.files(dir)`. Good call.

2022-02-09 15:30 UTC, seth127 commented on tests/testthat/test-read-spec-yaml.R
> +stories_only_cols <- c(
I would kind of prefer these go in `tests/testthat/setup.R` (and be all caps constants) just for consistency. Not a big deal if you have a reason to keep them here, but they seem potentially relevant to other tests not in this file.

Same with `yaml_file()` helper (move it to setup.R, not the all caps comment)

2022-02-09 15:36 UTC, kyleam commented on inst/yaml-input/stories-only-1.yaml
> +    S001 description
Thanks for spotting.  Will fix.

2022-02-09 16:02 UTC, kyleam commented
Thanks for the review @seth127.  Updated.

2022-02-09 16:24 UTC, seth127 approved these changes
Looks good, thanks. Sorry to make your linter mad.

2022-02-09 16:26 UTC, merged