Feat/parse GitHub issues
metrumresearchgroup/mrgvalprep pull request #35
Opened 2022-03-23 17:23 UTC by barrettk

Closes #32 
merge this PR first: https://github.com/metrumresearchgroup/mrgvalprep/pull/31

2022-03-23 21:03 UTC, barrettk commented
@seth127 

I havent pushed anything yet because im still trying to think about the most user friendly way to do this. Right now the functionality below would work (if I commit my latest change (very minor)):

```
MILESTONE <- c("v0.6.0", "v0.6.1")
spec <- parse_github_issues(org = ORG, repo = REPO, mile = MILESTONE, domain = DOMAIN); spec
```
![image](https://user-images.githubusercontent.com/18685116/159794424-da4e8093-3428-4e07-a72b-82f8dc67753c.png)


Which will pull in all issues associates with those two milestones. What im thinking about doing is modifying `gsheet_to_yaml` to allow neither `ss` or `sheet` to _have_ to be specified, but instead take in either A) a google sheet (normal functionality), or B) a dataframe returned by `parse_github_issues`. This would allow the other manipulating to still be used. If we move forward with that functionality, it would probably make sense to rename `gsheet_to_yaml` to something more broad, like `stories_to_yaml` or something. 

If you dont like that idea, we could create a separate function, but like you said we dont want to copy and paste code in multiple places.

Thoughts?

2022-03-23 21:44 UTC, barrettk commented
Proposed change that would also affect the other branch:

```
# New proposed function
stories_to_yaml <- function(
  sheet_df,
  file
){
  dd <- sheet_df %>%
    mutate(TestIds = sapply(.data$TestIds, toString))
  dl <- dd %>%
    rename(
      name = .data$StoryName,
      description = .data$StoryDescription,
      tests = .data$TestIds
    ) %>%
    split(seq(nrow(dd))) %>%
    setNames(dd$StoryId) %>%
    map(~ {
      .x <- as.list(.x)
      .x$StoryId <- NULL
      .x$tests <- unlist(stringr::str_split(.x$tests, ", *"))
      .x
    })
  yaml::write_yaml(dl, file)
  return(file)
}


# Test calls
## github milestones
MILESTONES <- c("v0.6.0", "v0.6.1")
parse_github_issues(org = ORG, repo = REPO, mile = MILESTONES, domain = DOMAIN) %>%
  stories_to_yaml(file = file.path(tempdir(), "temp.yaml")) %>%
  file.edit()

# google sheets
read_stories_only_gsheet(ss = "1LpSX5Rb1XM5-xmQ8Wl2gQjMT5-3FIkuCM7oZhSgvWeI") %>% 
  stories_to_yaml(file = file.path(tempdir(), "temp.yaml")) %>%
  file.edit()
```

2022-03-24 16:40 UTC, seth127 requested changes
Ok, after looking at this more, I like where your head is at, but I think the PR needs a little clean up to get it all the way there.

First off: I think you've found the right pattern here, except that user can just call `read_spec_gsheets()` instead of the (currently unexported) `read_stories_only_gsheet()`.

```r
## github milestones
MILESTONES <- c("v0.6.0", "v0.6.1")
parse_github_issues(org = ORG, repo = REPO, mile = MILESTONES, domain = DOMAIN) %>%
  stories_to_yaml(file = file.path(tempdir(), "temp.yaml")) %>%
  file.edit()

# google sheets
read_spec_gsheets(ss = "1LpSX5Rb1XM5-xmQ8Wl2gQjMT5-3FIkuCM7oZhSgvWeI") %>% 
  stories_to_yaml(file = file.path(tempdir(), "temp.yaml")) %>%
  file.edit()
```

Some other comments on the docs etc. below. Also, I think we should move this to it's own `stories-from-yaml.R` file, because it's not specific to gsheets anymore.

2022-03-24 16:40 UTC, seth127 commented on R/read-spec-gsheet.R
> +#' Read stories from a Google Sheet and write to a yaml file.
Need to rewrite these docs a bit. First off the title should be more generic "Write a stories tibble to YAML" or something.

Instead of the detailed "Options" section, put something like "takes a tibble with the following columns... For example, the tibble returned from either [parse_github_issues()] or [read_spec_gsheets()] (only Option 2 - Stories Only)."

2022-03-24 16:40 UTC, seth127 commented on R/read-spec-gsheet.R
> +#' @examples
I think you'll either have to remove this or add a [don't run](https://stackoverflow.com/questions/12038160/how-to-not-run-an-example-using-roxygen2) because roxygen will try to run this when it builds the package and it will fail without the `GITHUB_PAT` won't it?

I'm fine with just removing it, up to you though.

2022-03-24 16:40 UTC, seth127 commented on R/read-spec-gsheet.R
> +      .x$tests <- unlist(stringr::str_split(.x$tests, ", *"))
this regex is still wrong. See the regex on line 128 above.

2022-03-24 17:09 UTC, barrettk commented on R/read-spec-gsheet.R
> +#' @examples
Yes I just noticed this. I like the examples so Ill add a dont run wrapper to it

2022-03-24 19:28 UTC, seth127 approved these changes
Looks great. Nice work.

2022-03-24 19:31 UTC, merged