Fix/issue 41
metrumresearchgroup/mrgvalprep pull request #42
Opened 2022-04-14 19:00 UTC by barrettk

2022-04-14 19:01 UTC, barrettk commented
Added a new function argument that makes manually adding more tests easier, by allowing users to return the warning messages. Here's one use case:
```
missed_tests <- milestone_to_test_id(stories_df = stories_df, tests = test_ids, return_warnings = TRUE)$missing_milestones
missed_tests %>% dplyr::count(TestFile) %>% dplyr::arrange(desc(n))
```

![image](https://user-images.githubusercontent.com/18685116/163458697-857d288c-c85f-486d-bd08-0464e69064b3.png)

2022-04-14 19:29 UTC, barrettk commented
There are likely to be additional changes to the function when we tackle mrgsolve. Not sure if we want to pile them up on this PR, or create new ones as issues arise.

2022-04-15 13:11 UTC, kyleam requested changes
I see the following test failures:

```
── Error (test-end-to-end.R:38:3): Github end-to-end works ─────────────────────
Error in `assert_string(prefix)`: argument "prefix" is missing, with no default
Backtrace:
    ▆
 1. └─mrgvalprep::parse_github_issues(...) at test-end-to-end.R:38:2
 2.   └─checkmate::assert_string(prefix)
── Error (test-parse-github-issues.R:5:3): parse_github_issues() pulls from Github ──
Error in `assert_string(prefix)`: argument "prefix" is missing, with no default
Backtrace:
    ▆
 1. └─mrgvalprep::parse_github_issues(...) at test-parse-github-issues.R:5:2
 2.   └─checkmate::assert_string(prefix)
── Error (test-stories-to-yaml.R:37:3): stories_to_yaml() works correctly with github issues ──
Error in `assert_string(prefix)`: argument "prefix" is missing, with no default
Backtrace:
    ▆
 1. ├─... %>% ... at test-stories-to-yaml.R:37:2
 2. ├─mrgvalprep::stories_to_yaml(., file = file.path(tempdir(), "temp.yaml"))
 3. │ └─sheet_df %>% ...
 4. ├─dplyr::mutate(., TestIds = sapply(.data$TestIds, toString))
 5. └─mrgvalprep::parse_github_issues(...)
 6.   └─checkmate::assert_string(prefix)

[ FAIL 3 | WARN 0 | SKIP 1 | PASS 133 ]
Error: Test failures
Execution halted

1 error ✖ | 0 warnings ✔ | 2 notes ✖
Error: R CMD check found ERRORs
Execution halted
```

(And ideally the fix for gh-41 would come with a test.)

2022-04-15 13:11 UTC, kyleam commented on R/assign-test-ids.R
> +#' @param return_warnings logical (T/F). Whether or not to return the warning messages as well.
Hmm, this is confusingly worded.  You're not returning warning messages, you're returning the missing IDs and missing milestones that the warning messages were about.

2022-04-15 13:11 UTC, kyleam commented on R/assign-test-ids.R
> +#' @importFrom checkmate assert_string checkIntegerish
nit: you're using the `assert_string` spelling rather than `assertString` (good), so for consistency use `check_integerish` rather than `checkIntegerish`

2022-04-15 13:11 UTC, kyleam commented on R/assign-test-ids.R
> +  start_after = 1)
"after" seems like a misleading way to name it given that the generated test IDs will _include_ the value.

2022-04-15 13:11 UTC, kyleam commented on R/assign-test-ids.R
> +#' @param full_string logical. Whether or not to return the test_that call surrounding the test name .
spurious space before trailing period

2022-04-15 13:11 UTC, kyleam commented on R/assign-test-ids.R
> +  if(full_string){
This `full_string` branch is the largest part of this diff and then never used.  If it's a false start or not relevant at this point, please drop it.

2022-04-15 13:11 UTC, kyleam commented on R/assign-test-ids.R
> +
nit: please drop unconventional blank line between the test name and docstring

2022-04-15 13:11 UTC, kyleam commented on R/assign-test-ids.R
> +  from <- paste0("^( *(?:test_that|it) *\\( *['\"] *\\Q", from, "\\E)( *['\"])")
Here's this new diff and the one from `parse_tests` side by side (with `...` indicating the pasted in `from`):

```
replace_test_str  ^( *(?:test_that|it) *\\( *['\"] *\\Q...\\E)( *['\"])
parse_tests       ^ *(?:test_that|it) *\\( *(['\"])(?<name>.*)\\1 *, *(?:\\{ *)?$
```

Ideally this would be reworked so that there wouldn't be near-duplicate regexs, but this fix isn't really introducing that issue (just making it more obvious).  So I think that's fine to leave that be.

However, I do think if you're going to have near-duplicate regexs, you might as well eliminate all unnecessary differences between them.

Here's the ones I spot:

 * `parse_tests` is more correct in that it matches the delimiter (the `\\1` after the `name` group)

 * `parse_tests` anchors the string at the end (` *, *(?:\\{ *)?$`).  Given that `replace_test_str` is receiving names originally extracted by `replace_test_str`, I don't see a reason to have it not use the same anchor.

So my (untested) suggestion is that `replace_test_str` uses a regex like this:

```
from <- paste0("^( *(?:test_that|it) *\\( *['\"] *\\Q", from, "\\E)( *\\1 *, *(?:\\{ *)?)$")
```

2022-04-15 13:12 UTC, kyleam commented
> Not sure if we want to pile them up on this PR, or create new ones as issues arise.

Please create dedicated PRs.

2022-04-15 13:24 UTC, kyleam commented on R/assign-test-ids.R
> +  from <- paste0("^( *(?:test_that|it) *\\( *['\"] *\\Q", from, "\\E)( *['\"])")
I'll mark this as resolved since this comment just ends up being a "reading aloud" comment.

2022-04-15 15:04 UTC, barrettk commented on R/assign-test-ids.R
> +  if(full_string){
I did this to correct for a previous bug, bug then it ended up not being necessary. Part of me wanted to keep it in case I needed it later, though I guess I could always add it back if need be

2022-04-15 15:07 UTC, kyleam commented on R/assign-test-ids.R
> +  if(full_string){
Look at it from the standpoint of a reviewer trying to understand a changeset or you coming back to the code later. 
 Leaving unused cruft around just invites confusion.

2022-04-15 15:38 UTC, kyleam requested changes

2022-04-15 15:38 UTC, kyleam commented on NAMESPACE
> +importFrom(checkmate,check_integerish)
It looks like you must have mistakenly edited this by hand.  `checkIntegerish` is still used in `assign_test_ids`.

```
$ git show --oneline -s
6e72efc (HEAD, origin/fix/issue_41, refs/pull/origin/42) Fixed existing tests

$ git grep -n checkInteg
R/assign-test-ids.R:18:#' @importFrom checkmate assert_string checkIntegerish
R/assign-test-ids.R:28:  checkIntegerish(start_after, lower = 1)

$ git grep -n check_integ
NAMESPACE:16:importFrom(checkmate,check_integerish)
```

2022-04-15 15:50 UTC, barrettk commented on NAMESPACE
> +importFrom(checkmate,check_integerish)
@kyleam actually, for some reason it appears some of the changes I made got reverted accidentally. Just noticed one of the other changes I made got undone as well.

2022-04-15 17:21 UTC, kyleam approved these changes
A couple of comments, but none are blockers

2022-04-15 17:21 UTC, kyleam commented on tests/testthat/test-assign-test-ids.R
> +      fake_test <- parse_tests(fake_test_path)
This test isn't actually serving as a regression test for gh-41 because it will still pass with `replace_test_str`s old regex.  `parse_tests` had a more specific regex before this test, so you won't be able to detect the problem if `parse_tests` is collecting the tests.

```
$ git show --oneline -s
ab60d99 (HEAD, origin/fix/issue_41, refs/pull/origin/42) finished restoring previous changes, added test for issue 41, and fixed other tests
```

Revert regex change from a69f336:

```diff
diff --git a/R/assign-test-ids.R b/R/assign-test-ids.R
index 098a74c..d535fcf 100644
--- a/R/assign-test-ids.R
+++ b/R/assign-test-ids.R
@@ -222,7 +222,7 @@ print_and_capture <- function(x)
 #' @importFrom stringi stri_replace_all_regex
 #' @keywords internal
 replace_test_str <- function(test_file, from, to){
-  from <- paste0("^( *(?:test_that|it) *\\( *['\"] *\\Q", from, "\\E)( *['\"])")
+  from <- paste0("(['\"] *\\Q", from, "\\E)( *['\"])")
   to <- paste0("$1 [", to, "]$2")

   test_file_new <- stri_replace_all_regex(test_file, from, to, vectorize_all=FALSE)
```

Tests still pass:

```
$ Rscript -e 'devtools::test(filter = "assign-test-ids")'
ℹ Loading mrgvalprep
ℹ Testing mrgvalprep
✔ | F W S  OK | Context
✔ |        12 | assign-test-ids [10.2s]

[ FAIL 0 | WARN 0 | SKIP 0 | PASS 12 ]
```

However, that does leave unstaged changes in `inst/fake-tests/new_tests/test-repeated-text.R`, so the regression would probably be noticed, but "leaves my working tree dirty" of course isn't a great test assertion.

<details>
<summary>diff</summary>

```
$ git diff -- inst
diff --git a/inst/fake-tests/new_tests/test-repeated-text.R b/inst/fake-tests/new_tests/test-repeated-text.R
index e61a102..0798dfa 100644
--- a/inst/fake-tests/new_tests/test-repeated-text.R
+++ b/inst/fake-tests/new_tests/test-repeated-text.R
@@ -1,16 +1,16 @@
 context("Fake Test - repeated text")

 test_that("Fake test with same text repeated [MRGVAL-TEST-0098]", {
-  str <- "Fake test with same text repeated"
+  str <- "Fake test with same text repeated [MRGVAL-TEST-0098]"
   expect_true(is.character(str))
 })

 test_that("Fake test with same text repeated [MRGVAL-TEST-0098]", {
-  str <- "Fake test with same text repeated"
+  str <- "Fake test with same text repeated [MRGVAL-TEST-0098]"
   expect_true(is.character(str))
 })

 test_that("Fake test with same text repeated 2 [MRGVAL-TEST-0099]", {
-  str <- "Fake test with same text repeated 2"
+  str <- "Fake test with same text repeated 2 [MRGVAL-TEST-0099]"
   expect_true(is.character(str))
 })
```

</details>

One way to improve the situation would be to overwrite in a temp directory copy and then compare to the tracked golden file ([my related comment from pr 36](https://github.com/metrumresearchgroup/mrgvalprep/pull/36#discussion_r843290661)).

I'll leave it up to you whether you want to try to address this.

2022-04-15 17:21 UTC, kyleam commented on R/assign-test-ids.R
> +  setNames(test_names, rep(basename(test_file), length(test_names)))
nit: lines 148-151 are over-indented

2022-04-15 17:25 UTC, kyleam commented
Note that tightening this regex also fixes #40

2022-04-18 17:29 UTC, merged